create database QL_CUAHANG
go
use QL_CUAHANG
go
CREATE TABLE LOAITAIKHOAN(
	MALOAITAIKHOAN NVARCHAR(50) PRIMARY KEY,
	TENLOAITAIKHOAN NVARCHAR(50)
)
GO
create TABLE TAIKHOAN(
	TENDANGNHAP NVARCHAR(50) PRIMARY KEY,
	MATKHAU NVARCHAR(50),
	HOTEN NVARCHAR(50),
	GIOITINH NVARCHAR(10),
	NGAYSINH NVARCHAR(50),
	DIACHI NVARCHAR(50),
	SODIENTHOAI NVARCHAR(20),
	MALOAITAIKHOAN NVARCHAR(50)
	FOREIGN KEY(MALOAITAIKHOAN) REFERENCES LOAITAIKHOAN(MALOAITAIKHOAN)
)
GO
CREATE TABLE KHACHHANG(
	MAKHACHHANG NVARCHAR(50) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	GIOITINH NVARCHAR(10),
	SODIENTHOAI NVARCHAR(20)
)
GO
CREATE TABLE PHIEUXUATHANG(
	MAPHIEU NVARCHAR(50) PRIMARY KEY,
	NGUOIQUANLI NVARCHAR(50),--NGƯỜI BÁN HÀNG
	MAKHACHHANG NVARCHAR(50),
	NGAYXUAT NVARCHAR(50),
	FOREIGN KEY(MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG)
)
GO
CREATE TABLE HANGHOA(
	MAHANGHOA NVARCHAR(50) PRIMARY KEY,
	TENHANGHOA NVARCHAR(50),
	DONGIA FLOAT,
	SOLUONG FLOAT,
	THANHPHAN NVARCHAR(100),
	DONVITINH NVARCHAR(50)

)
GO
CREATE TABLE CHITIETXUAT(
	MACHITIETXUAT NVARCHAR(50) PRIMARY KEY,
	MAPHIEUXUAT NVARCHAR(50),
	MAHANGHOA NVARCHAR(50),
	SOLUONG FLOAT,
	DONGIA FLOAT,
	FOREIGN KEY(MAPHIEUXUAT) REFERENCES PHIEUXUATHANG(MAPHIEU),
	FOREIGN KEY(MAHANGHOA) REFERENCES HANGHOA(MAHANGHOA)
)
GO
CREATE TABLE NHACUNGCAP(
	MANHACUNGCAP NVARCHAR(50) PRIMARY KEY,
	TENNHACUNGCAP NVARCHAR(50),
	DIACHI NVARCHAR(50),
	SODIENTHOAI NVARCHAR(20)
)
GO
CREATE TABLE PHIEUNHAPHANG(
	MAPHIEUNHAP NVARCHAR(50) PRIMARY KEY,
	NGUOIQUANLY NVARCHAR(50),
	MANHACUNGCAP NVARCHAR(50),
	NGAYNHAP NVARCHAR(50),	
	FOREIGN KEY (MANHACUNGCAP) REFERENCES NHACUNGCAP(MANHACUNGCAP),
	FOREIGN KEY (NGUOIQUANLY) REFERENCES TAIKHOAN(TENDANGNHAP)
)
GO
CREATE TABLE HOADON(
	MAHOADON NVARCHAR(50) PRIMARY KEY,
	NHANVIEN NVARCHAR(50),
	NGAYLAP NVARCHAR(50),
	FOREIGN KEY (NHANVIEN) REFERENCES TAIKHOAN(TENDANGNHAP)
)
GO
CREATE TABLE CHITIETHOADON(
	MACHITIET NVARCHAR(50) PRIMARY KEY,
	MAHOADON NVARCHAR(50),
	MAHANGHOA NVARCHAR(50),
	SOLUONG FLOAT,
	DONGIA FLOAT,
	FOREIGN KEY(MAHOADON) REFERENCES HOADON(MAHOADON),
	FOREIGN KEY(MAHANGHOA) REFERENCES HANGHOA(MAHANGHOA)
)

